//------------------------------------C O N S T A N T S----------------------------------------------
export const DashboardActionTypes = {
    DASHBOARD_DATA_FIRST: '@@dashboard/DASHBOARD_DATA_FIRST',
    DASHBOARD_DATA_LOADING: '@@dashboard/DASHBOARD_DATA_LOADING',
    DASHBOARD_DATA_SUCCESS: '@@dashboard/DASHBOARD_DATA_SUCCESS',
    DASHBOARD_DATA_ERROR: '@@dashboard/DASHBOARD_DATA_ERROR',
    DASHBOARD_DATA_RESET: '@@dashboard/DASHBOARD_DATA_RESET',

    STOCKIN_TRANS_LIST_FIRST: 'STOCKIN_TRANS_LIST_FIRST',
    STOCKIN_TRANS_LIST_LOADING: 'STOCKIN_TRANS_LIST_LOADING',
    STOCKIN_TRANS_LIST_SUCCESS: 'STOCKIN_TRANS_LIST_SUCCESS',
    STOCKIN_TRANS_LIST_ERROR: 'STOCKIN_TRANS_LIST_ERROR',
    STOCKIN_TRANS_LIST_RESET: 'STOCKIN_TRANS_LIST_RESET',

    DISPATCH_LIST_FIRST: 'DISPATCH_LIST_FIRST',
    DISPATCH_LIST_LOADING: 'DISPATCH_LIST_LOADING',
    DISPATCH_LIST_SUCCESS: 'DISPATCH_LIST_SUCCESS',
    DISPATCH_LIST_ERROR: 'DISPATCH_LIST_ERROR',
    DISPATCH_LIST_RESET: 'DISPATCH_LIST_RESET',
};