//------------------------------------C O N S T A N T S----------------------------------------------
export const DashboardActionTypes = {
    DASHBOARD_DATA_FIRST: '@@dashboard/DASHBOARD_DATA_FIRST',
    DASHBOARD_DATA_LOADING: '@@dashboard/DASHBOARD_DATA_LOADING',
    DASHBOARD_DATA_SUCCESS: '@@dashboard/DASHBOARD_DATA_SUCCESS',
    DASHBOARD_DATA_ERROR: '@@dashboard/DASHBOARD_DATA_ERROR',
    DASHBOARD_DATA_RESET: '@@dashboard/DASHBOARD_DATA_RESET',

    STOCKIN_TRANS_LIST_FIRST: 'STOCKIN_TRANS_LIST_FIRST',
    STOCKIN_TRANS_LIST_LOADING: 'STOCKIN_TRANS_LIST_LOADING',
    STOCKIN_TRANS_LIST_SUCCESS: 'STOCKIN_TRANS_LIST_SUCCESS',
    STOCKIN_TRANS_LIST_ERROR: 'STOCKIN_TRANS_LIST_ERROR',
    STOCKIN_TRANS_LIST_RESET: 'STOCKIN_TRANS_LIST_RESET',

    DISPATCH_LIST_FIRST: 'DISPATCH_LIST_FIRST',
    DISPATCH_LIST_LOADING: 'DISPATCH_LIST_LOADING',
    DISPATCH_LIST_SUCCESS: 'DISPATCH_LIST_SUCCESS',
    DISPATCH_LIST_ERROR: 'DISPATCH_LIST_ERROR',
    DISPATCH_LIST_RESET: 'DISPATCH_LIST_RESET',

    GET_STOCK_REPORT_FIRST: 'GET_STOCK_REPORT_FIRST',
    GET_STOCK_REPORT_LOADING: 'GET_STOCK_REPORT_LOADING',
    GET_STOCK_REPORT_SUCCESS: 'GET_STOCK_REPORT_SUCCESS',
    GET_STOCK_REPORT_ERROR: 'GET_STOCK_REPORT_ERROR',
    GET_STOCK_REPORT_RESET: 'GET_STOCK_REPORT_RESET',

    GET_RECENT_TRANS_FIRST: 'GET_RECENT_TRANS_FIRST',
    GET_RECENT_TRANS_LOADING: 'GET_RECENT_TRANS_LOADING',
    GET_RECENT_TRANS_SUCCESS: 'GET_RECENT_TRANS_SUCCESS',
    GET_RECENT_TRANS_ERROR: 'GET_RECENT_TRANS_ERROR',
    GET_RECENT_TRANS_RESET: 'GET_RECENT_TRANS_RESET',

    GET_LOW_STOCK_FIRST: 'GET_LOW_STOCK_FIRST',
    GET_LOW_STOCK_LOADING: 'GET_LOW_STOCK_LOADING',
    GET_LOW_STOCK_SUCCESS: 'GET_LOW_STOCK_SUCCESS',
    GET_LOW_STOCK_ERROR: 'GET_LOW_STOCK_ERROR',
    GET_LOW_STOCK_RESET: 'GET_LOW_STOCK_RESET',
};