//------------------------------------C O N S T A N T S----------------------------------------------
export const StockActionTypes = {
    STOCK_LIST_FIRST: 'STOCK_LIST_FIRST',
    STOCK_LIST_LOADING: 'STOCK_LIST_LOADING',
    STOCK_LIST_SUCCESS: 'STOCK_LIST_SUCCESS',
    STOCK_LIST_ERROR: 'STOCK_LIST_ERROR',
    STOCK_LIST_RESET: 'STOCK_LIST_RESET',

    CREATE_STOCK_FIRST: 'CREATE_STOCK_FIRST',
    CREATE_STOCK_LOADING: 'CREATE_STOCK_LOADING',
    CREATE_STOCK_SUCCESS: 'CREATE_STOCK_SUCCESS',
    CREATE_STOCK_ERROR: 'CREATE_STOCK_ERROR',
    CREATE_STOCK_RESET: 'CREATE_STOCK_RESET',

    UPDATE_STOCK_FIRST: 'UPDATE_STOCK_FIRST',
    UPDATE_STOCK_LOADING: 'UPDATE_STOCK_LOADING',
    UPDATE_STOCK_SUCCESS: 'UPDATE_STOCK_SUCCESS',
    UPDATE_STOCK_ERROR: 'UPDATE_STOCK_ERROR',
    UPDATE_STOCK_RESET: 'UPDATE_STOCK_RESET',

};