//------------------------------------C O N S T A N T S----------------------------------------------
export const CustomerActionTypes = {
    CUSTOMER_LIST_FIRST: 'CUSTOMER_LIST_FIRST',
    CUSTOMER_LIST_LOADING: 'CUSTOMER_LIST_LOADING',
    CUSTOMER_LIST_SUCCESS: 'CUSTOMER_LIST_SUCCESS',
    CUSTOMER_LIST_ERROR: 'CUSTOMER_LIST_ERROR',
    CUSTOMER_LIST_RESET: 'CUSTOMER_LIST_RESET',

    CREATE_CUSTOMER_FIRST: 'CREATE_CUSTOMER_FIRST',
    CREATE_CUSTOMER_LOADING: 'CREATE_CUSTOMER_LOADING',
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_ERROR: 'CREATE_CUSTOMER_ERROR',
    CREATE_CUSTOMER_RESET: 'CREATE_CUSTOMER_RESET',

    UPDATE_CUSTOMER_FIRST: 'UPDATE_CUSTOMER_FIRST',
    UPDATE_CUSTOMER_LOADING: 'UPDATE_CUSTOMER_LOADING',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_ERROR: 'UPDATE_CUSTOMER_ERROR',
    UPDATE_CUSTOMER_RESET: 'UPDATE_CUSTOMER_RESET',

    DELETE_CUSTOMER_FIRST: 'DELETE_CUSTOMER_FIRST',
    DELETE_CUSTOMER_LOADING: 'DELETE_CUSTOMER_LOADING',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_ERROR: 'DELETE_CUSTOMER_ERROR',
    DELETE_CUSTOMER_RESET: 'DELETE_CUSTOMER_RESET',

    LISTING_CUSTOMER_FIRST: 'LISTING_CUSTOMER_FIRST',
    LISTING_CUSTOMER_LOADING: 'LISTING_CUSTOMER_LOADING',
    LISTING_CUSTOMER_SUCCESS: 'LISTING_CUSTOMER_SUCCESS',
    LISTING_CUSTOMER_ERROR: 'LISTING_CUSTOMER_ERROR',
    LISTING_CUSTOMER_RESET: 'LISTING_CUSTOMER_RESET',
};