//------------------------------------C O N S T A N T S----------------------------------------------
export const WarehouseActionTypes = {

    CREATE_WAREHOUSE_FIRST: 'CREATE_WAREHOUSE_FIRST',
    CREATE_WAREHOUSE_LOADING: 'CREATE_WAREHOUSE_LOADING',
    CREATE_WAREHOUSE_SUCCESS: 'CREATE_WAREHOUSE_SUCCESS',
    CREATE_WAREHOUSE_ERROR: 'CREATE_WAREHOUSE_ERROR',
    CREATE_WAREHOUSE_RESET: 'CREATE_WAREHOUSE_RESET',

    GET_WAREHOUSE_FIRST: 'GET_WAREHOUSE_FIRST',
    GET_WAREHOUSE_LOADING: 'GET_WAREHOUSE_LOADING',
    GET_WAREHOUSE_SUCCESS: 'GET_WAREHOUSE_SUCCESS',
    GET_WAREHOUSE_ERROR: 'GET_WAREHOUSE_ERROR',
    GET_WAREHOUSE_RESET: 'GET_WAREHOUSE_RESET',

    UPDATE_WAREHOUSE_FIRST: 'UPDATE_WAREHOUSE_FIRST',
    UPDATE_WAREHOUSE_LOADING: 'UPDATE_WAREHOUSE_LOADING',
    UPDATE_WAREHOUSE_SUCCESS: 'UPDATE_WAREHOUSE_SUCCESS',
    UPDATE_WAREHOUSE_ERROR: 'UPDATE_WAREHOUSE_ERROR',
    UPDATE_WAREHOUSE_RESET: 'UPDATE_WAREHOUSE_RESET',

    DELETE_WAREHOUSE_FIRST: 'DELETE_WAREHOUSE_FIRST',
    DELETE_WAREHOUSE_LOADING: 'DELETE_WAREHOUSE_LOADING',
    DELETE_WAREHOUSE_SUCCESS: 'DELETE_WAREHOUSE_SUCCESS',
    DELETE_WAREHOUSE_ERROR: 'DELETE_WAREHOUSE_ERROR',
    DELETE_WAREHOUSE_RESET: 'DELETE_WAREHOUSE_RESET',

    SEARCH_WAREHOUSE_FIRST: 'SEARCH_WAREHOUSE_FIRST',
    SEARCH_WAREHOUSE_LOADING: 'SEARCH_WAREHOUSE_LOADING',
    SEARCH_WAREHOUSE_SUCCESS: 'SEARCH_WAREHOUSE_SUCCESS',
    SEARCH_WAREHOUSE_ERROR: 'SEARCH_WAREHOUSE_ERROR',
    SEARCH_WAREHOUSE_RESET: 'SEARCH_WAREHOUSE_RESET',
};