//------------------------------------C O N S T A N T S----------------------------------------------
export const NotificationActionTypes = {

    GET_NOTIFICATION_FIRST: 'GET_NOTIFICATION_FIRST',
    GET_NOTIFICATION_LOADING: 'GET_NOTIFICATION_LOADING',
    GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
    GET_NOTIFICATION_ERROR: 'GET_NOTIFICATION_ERROR',

    // CREATE_NOTIFICATION_FIRST: 'CREATE_NOTIFICATION_FIRST',
    // CREATE_NOTIFICATION_LOADING: 'CREATE_NOTIFICATION_LOADING',
    // CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    // CREATE_NOTIFICATION_ERROR: 'CREATE_NOTIFICATION_ERROR',

    // UPDATE_NOTIFICATION_DATA_FIRST: 'UPDATE_NOTIFICATION_DATA_FIRST',
    // UPDATE_NOTIFICATION_DATA_LOADING: 'UPDATE_NOTIFICATION_DATA_LOADING',
    // UPDATE_NOTIFICATION_DATA_SUCCESS: 'UPDATE_NOTIFICATION_DATA_SUCCESS',
    // UPDATE_NOTIFICATION_DATA_RESET: 'UPDATE_NOTIFICATION_DATA_RESET',
    // UPDATE_NOTIFICATION_DATA_ERROR: 'UPDATE_NOTIFICATION_DATA_ERROR',

    // STATE_EMPTY_FIRST: 'STATE_EMPTY_FIRST',
    // STATE_EMPTY_SUCCESS: 'STATE_EMPTY_SUCCESS',

};