//------------------------------------C O N S T A N T S----------------------------------------------
export const DispatchActionTypes = {
    GET_DISPATCH_LIST: 'GET_DISPATCH_LIST',
    GET_DISPATCH_LIST_LOADING: 'GET_DISPATCH_LIST_LOADING',
    GET_DISPATCH_LIST_SUCCESS: 'GET_DISPATCH_LIST_SUCCESS',
    GET_DISPATCH_LIST_ERROR: 'GET_DISPATCH_LIST_ERROR',
    GET_DISPATCH_LIST_RESET: 'GET_DISPATCH_LIST_RESET',

    CREATE_DISPATCH_FIRST: 'CREATE_DISPATCH_FIRST',
    CREATE_DISPATCH_LOADING: 'CREATE_DISPATCH_LOADING',
    CREATE_DISPATCH_SUCCESS: 'CREATE_DISPATCH_SUCCESS',
    CREATE_DISPATCH_ERROR: 'CREATE_DISPATCH_ERROR',
    CREATE_DISPATCH_RESET: 'CREATE_DISPATCH_RESET',

    UPDATE_DISPATCH_FIRST: 'UPDATE_DISPATCH_FIRST',
    UPDATE_DISPATCH_LOADING: 'UPDATE_DISPATCH_LOADING',
    UPDATE_DISPATCH_SUCCESS: 'UPDATE_DISPATCH_SUCCESS',
    UPDATE_DISPATCH_ERROR: 'UPDATE_DISPATCH_ERROR',
    UPDATE_DISPATCH_RESET: 'UPDATE_DISPATCH_RESET',

    DELETE_DISPATCH_FIRST: 'DELETE_DISPATCH_FIRST',
    DELETE_DISPATCH_LOADING: 'DELETE_DISPATCH_LOADING',
    DELETE_DISPATCH_SUCCESS: 'DELETE_DISPATCH_SUCCESS',
    DELETE_DISPATCH_ERROR: 'DELETE_DISPATCH_ERROR',
    DELETE_DISPATCH_RESET: 'DELETE_DISPATCH_RESET',

    CREATE_STOCK_CHECK_FIRST: 'CREATE_STOCK_CHECK_FIRST',
    CREATE_STOCK_CHECK_LOADING: 'CREATE_STOCK_CHECK_LOADING',
    CREATE_STOCK_CHECK_SUCCESS: 'CREATE_STOCK_CHECK_SUCCESS',
    CREATE_STOCK_CHECK_ERROR: 'CREATE_STOCK_CHECK_ERROR',
    CREATE_STOCK_CHECK_RESET: 'CREATE_STOCK_CHECK_RESET',

    UPDATE_DISPATCH_PRODUCT_FIRST: 'UPDATE_DISPATCH_PRODUCT_FIRST',
    UPDATE_DISPATCH_PRODUCT_LOADING: 'UPDATE_DISPATCH_PRODUCT_LOADING',
    UPDATE_DISPATCH_PRODUCT_SUCCESS: 'UPDATE_DISPATCH_PRODUCT_SUCCESS',
    UPDATE_DISPATCH_PRODUCT_ERROR: 'UPDATE_DISPATCH_PRODUCT_ERROR',
    UPDATE_DISPATCH_PRODUCT_RESET: 'UPDATE_DISPATCH_PRODUCT_RESET',

    DELETE_DISPATCH_PRODUCT_FIRST: 'DELETE_DISPATCH_PRODUCT_FIRST',
    DELETE_DISPATCH_PRODUCT_LOADING: 'DELETE_DISPATCH_PRODUCT_LOADING',
    DELETE_DISPATCH_PRODUCT_SUCCESS: 'DELETE_DISPATCH_PRODUCT_SUCCESS',
    DELETE_DISPATCH_PRODUCT_ERROR: 'DELETE_DISPATCH_PRODUCT_ERROR',
    DELETE_DISPATCH_PRODUCT_RESET: 'DELETE_DISPATCH_PRODUCT_RESET',
};