//------------------------------------C O N S T A N T S----------------------------------------------
export const InventoryActionTypes = {
    PRODUCT_LIST_FIRST: 'PRODUCT_LIST_FIRST',
    PRODUCT_LIST_LOADING: 'PRODUCT_LIST_LOADING',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_ERROR: 'PRODUCT_LIST_ERROR',
    PRODUCT_LIST_RESET: 'PRODUCT_LIST_RESET',

    CREATE_PRODUCT_FIRST: 'CREATE_PRODUCT_FIRST',
    CREATE_PRODUCT_LOADING: 'CREATE_PRODUCT_LOADING',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
    CREATE_PRODUCT_RESET: 'CREATE_PRODUCT_RESET',

    UPDATE_PRODUCT_FIRST: 'UPDATE_PRODUCT_FIRST',
    UPDATE_PRODUCT_LOADING: 'UPDATE_PRODUCT_LOADING',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
    UPDATE_PRODUCT_RESET: 'UPDATE_PRODUCT_RESET',

    DELETE_PRODUCT_FIRST: 'DELETE_PRODUCT_FIRST',
    DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
    DELETE_PRODUCT_RESET: 'DELETE_PRODUCT_RESET',

    SEARCH_PRODUCT_FIRST: 'SEARCH_PRODUCT_FIRST',
    SEARCH_PRODUCT_LOADING: 'SEARCH_PRODUCT_LOADING',
    SEARCH_PRODUCT_SUCCESS: 'SEARCH_PRODUCT_SUCCESS',
    SEARCH_PRODUCT_ERROR: 'SEARCH_PRODUCT_ERROR',
    SEARCH_PRODUCT_RESET: 'SEARCH_PRODUCT_RESET',

};