//------------------------------------C O N S T A N T S----------------------------------------------
export const SupplierActionTypes = {
    SUPPLIER_LIST_FIRST: 'SUPPLIER_LIST_FIRST',
    SUPPLIER_LIST_LOADING: 'SUPPLIER_LIST_LOADING',
    SUPPLIER_LIST_SUCCESS: 'SUPPLIER_LIST_SUCCESS',
    SUPPLIER_LIST_ERROR: 'SUPPLIER_LIST_ERROR',
    SUPPLIER_LIST_RESET: 'SUPPLIER_LIST_RESET',

    CREATE_SUPPLIER_FIRST: 'CREATE_SUPPLIER_FIRST',
    CREATE_SUPPLIER_LOADING: 'CREATE_SUPPLIER_LOADING',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_ERROR: 'CREATE_SUPPLIER_ERROR',
    CREATE_SUPPLIER_RESET: 'CREATE_SUPPLIER_RESET',

    UPDATE_SUPPLIER_FIRST: 'UPDATE_SUPPLIER_FIRST',
    UPDATE_SUPPLIER_LOADING: 'UPDATE_SUPPLIER_LOADING',
    UPDATE_SUPPLIER_SUCCESS: 'UPDATE_SUPPLIER_SUCCESS',
    UPDATE_SUPPLIER_ERROR: 'UPDATE_SUPPLIER_ERROR',
    UPDATE_SUPPLIER_RESET: 'UPDATE_SUPPLIER_RESET',

    DELETE_SUPPLIER_FIRST: 'DELETE_SUPPLIER_FIRST',
    DELETE_SUPPLIER_LOADING: 'DELETE_SUPPLIER_LOADING',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIER_ERROR: 'DELETE_SUPPLIER_ERROR',
    DELETE_SUPPLIER_RESET: 'DELETE_SUPPLIER_RESET',

    LISTING_SUPPLIER_FIRST: 'LISTING_SUPPLIER_FIRST',
    LISTING_SUPPLIER_LOADING: 'LISTING_SUPPLIER_LOADING',
    LISTING_SUPPLIER_SUCCESS: 'LISTING_SUPPLIER_SUCCESS',
    LISTING_SUPPLIER_ERROR: 'LISTING_SUPPLIER_ERROR',
    LISTING_SUPPLIER_RESET: 'LISTING_SUPPLIER_RESET',
};