//------------------------------------C O N S T A N T S----------------------------------------------
export const StockInActionTypes = {
    STOCKIN_LIST_FIRST: 'STOCKIN_LIST_FIRST',
    STOCKIN_LIST_LOADING: 'STOCKIN_LIST_LOADING',
    STOCKIN_LIST_SUCCESS: 'STOCKIN_LIST_SUCCESS',
    STOCKIN_LIST_ERROR: 'STOCKIN_LIST_ERROR',
    STOCKIN_LIST_RESET: 'STOCKIN_LIST_RESET',

    CREATE_STOCKIN_FIRST: 'CREATE_STOCKIN_FIRST',
    CREATE_STOCKIN_LOADING: 'CREATE_STOCKIN_LOADING',
    CREATE_STOCKIN_SUCCESS: 'CREATE_STOCKIN_SUCCESS',
    CREATE_STOCKIN_ERROR: 'CREATE_STOCKIN_ERROR',
    CREATE_STOCKIN_RESET: 'CREATE_STOCKIN_RESET',

    UPDATE_STOCKIN_FIRST: 'UPDATE_STOCKIN_FIRST',
    UPDATE_STOCKIN_LOADING: 'UPDATE_STOCKIN_LOADING',
    UPDATE_STOCKIN_SUCCESS: 'UPDATE_STOCKIN_SUCCESS',
    UPDATE_STOCKIN_ERROR: 'UPDATE_STOCKIN_ERROR',
    UPDATE_STOCKIN_RESET: 'UPDATE_STOCKIN_RESET',

    DELETE_STOCKIN_FIRST: 'DELETE_STOCKIN_FIRST',
    DELETE_STOCKIN_LOADING: 'DELETE_STOCKIN_LOADING',
    DELETE_STOCKIN_SUCCESS: 'DELETE_STOCKIN_SUCCESS',
    DELETE_STOCKIN_ERROR: 'DELETE_STOCKIN_ERROR',
    DELETE_STOCKIN_RESET: 'DELETE_STOCKIN_RESET',
};