//------------------------------------C O N S T A N T S----------------------------------------------
export const UsersActionTypes = {
    USERS_LIST_FIRST: 'USERS_LIST_FIRST',
    USERS_LIST_LOADING: 'USERS_LIST_LOADING',
    USERS_LIST_SUCCESS: 'USERS_LIST_SUCCESS',
    USERS_LIST_ERROR: 'USERS_LIST_ERROR',
    USERS_LIST_RESET: 'USERS_LIST_RESET',

    CREATE_USERS_FIRST: 'CREATE_USERS_FIRST',
    CREATE_USERS_LOADING: 'CREATE_USERS_LOADING',
    CREATE_USERS_SUCCESS: 'CREATE_USERS_SUCCESS',
    CREATE_USERS_ERROR: 'CREATE_USERS_ERROR',
    CREATE_USERS_RESET: 'CREATE_USERS_RESET',

    UPDATE_USERS_FIRST: 'UPDATE_USERS_FIRST',
    UPDATE_USERS_LOADING: 'UPDATE_USERS_LOADING',
    UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
    UPDATE_USERS_ERROR: 'UPDATE_USERS_ERROR',
    UPDATE_USERS_RESET: 'UPDATE_USERS_RESET',

    DELETE_USERS_FIRST: 'DELETE_USERS_FIRST',
    DELETE_USERS_LOADING: 'DELETE_USERS_LOADING',
    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_ERROR: 'DELETE_USERS_ERROR',
    DELETE_USERS_RESET: 'DELETE_USERS_RESET',

    LISTING_USERS_FIRST: 'LISTING_USERS_FIRST',
    LISTING_USERS_LOADING: 'LISTING_USERS_LOADING',
    LISTING_USERS_SUCCESS: 'LISTING_USERS_SUCCESS',
    LISTING_USERS_ERROR: 'LISTING_USERS_ERROR',
    LISTING_USERS_RESET: 'LISTING_USERS_RESET',

};